# Generated by Django 5.1.2 on 2024-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_category_agriculturalproduct_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agriculturalproduct",
            name="image_url",
        ),
        migrations.AddField(
            model_name="agriculturalproduct",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
