# Generated by Django 4.2 on 2024-12-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
