# Generated by Django 4.2 on 2024-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_purchase_is_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="address_line1",
            field=models.CharField(default="默认地址", max_length=255),
        ),
        migrations.AddField(
            model_name="purchase",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="purchase",
            name="city",
            field=models.CharField(default="默认城市", max_length=100),
        ),
        migrations.AddField(
            model_name="purchase",
            name="state",
            field=models.CharField(default="默认省份", max_length=100),
        ),
        migrations.AddField(
            model_name="purchase",
            name="zip_code",
            field=models.CharField(default="000000", max_length=20),
        ),
    ]
